#define HOLSTER_PRIMARY 0
#define HOLSTER_SECONDARY 1
#define HOLSTER_TERTIARY 2

#define WEAPON_TASER "x26_taser"

#define HOLSTER_INDEX_WEAPON 0
#define HOLSTER_INDEX_WEAPON_MAGAZINE 1
#define HOLSTER_INDEX_WEAPON_MAGAZINE_COUNT 2
#define HOLSTER_INDEX_WEAPON_ITEMS 3
